package com.radiodns;

import android.app.Application;

import com.facebook.react.ReactApplication;
import com.radiodns.auto.RadioDNSAutoPackage;
import com.radiodns.exitApp.RadioDNSExitAppPackage;
import com.radiodns.notificationControl.RadioDNSControlNotificationPackage;
import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
import com.brentvatne.react.ReactVideoPackage;
import com.oblador.vectoricons.VectorIconsPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;

/**
 * Main application class generated by React Native. Use it as an entry point for all native modules.
 */
public class MainApplication extends Application implements ReactApplication {

    private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
            return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
            return Arrays.<ReactPackage>asList(
                    new MainReactPackage(),
                    new RNGestureHandlerPackage(),
                    new ReactVideoPackage(),
                    new VectorIconsPackage(),
                    new RadioDNSAutoPackage(),
                    new RadioDNSControlNotificationPackage(),
                    new RadioDNSExitAppPackage()
            );
        }

        @Override
        protected String getJSMainModuleName() {
            return "index";
        }
    };

    @Override
    public ReactNativeHost getReactNativeHost() {
        return mReactNativeHost;
    }

    @Override
    public void onCreate() {
        super.onCreate();
        SoLoader.init(this, /* native exopackage */ false);
    }
}
